### ISSUE TITLE
503 Service Unavailable after deploying Sava_1.0.yaml

### ISSUE THREAD

**Issue by olafmol** [magneticio/sava#2]
Running through the getting started steps, i get a 503 error after deploying the first Sava_1.0.yaml to Vamp. After POSTing the YAML file from the Sava repo i get a 202:

 {"name":"3981a3be-d312-47b7-bbdb-6f07c0ce6c06","endpoints":{"sava.port":"9050"},"clusters":{"sava":{"services":[{"state":{"name":"ReadyForDeployment","started_at":"2015-06-09T13:07:34.037Z"},"breed":{"name":"sava:1.0.0","deployable":"magneticio/sava:1.0.0","ports":{"port":"80/http"},"environment_variables":{},"constants":{},"dependencies":{}},"scale":{"cpu":0.3,"memory":512.0,"instances":1},"routing":{"weight":100,"filters":[]},"servers":[],"dependencies":{},"dialects":{}}],"routes":{"80":33003},"dialects":{}}},"ports":{},"environment_variables":{},"constants":{},"hosts":{"sava":"localhost"}}

Marathon reports a running application. When trying to access the application on the blueprint-defined port (9050) and the IP where VAMP is running (in my case 192.168.59.103) i only see a 503 error in my safari browser.

I'm not sure if i need to do something with the Sava docker containers? I assume that the blueprints are pointing to the public Docker repo and VAMP can access these containers without any issue. 

BTW, I used the "all in one VAMP install"

**Comment by dragoslav** [comment]
It seems as a problem with configuration. These are routes (http://192.168.59.103:10001/v1/routes):
```json
[
  {
    "name": "1f216ce9-0719-4a65-9463-8a177597aa9e_sava_80",
    "port": 33000,
    "protocol": "http",
    "httpQuota": {},
    "tcpQuota": {},
    "filters": [],
    "services": [
      {
        "name": "sava:1.0.0",
        "weight": 100,
        "servers": [
          {
            "name": "2cc411eb9e1477622a753d60c27cd1bc4a2ec7f",
            "host": "192.168.59.103",
            "port": 31556
          }
        ]
      }
    ]
  },
  {
    "name": "1f216ce9-0719-4a65-9463-8a177597aa9e_9050",
    "port": 9050,
    "protocol": "tcp",
    "httpQuota": {},
    "tcpQuota": {},
    "filters": [],
    "services": [
      {
        "name": "sava.ports.port",
        "weight": 100,
        "servers": [
          {
            "name": "1f216ce9-0719-4a65-9463-8a177597aa9e_9050",
            "host": "localhost",
            "port": 33000
          }
        ]
      }
    ]
  }
]

```

If you go directly to http://192.168.59.103:33000 skipping the additional endpoint route you get the valid response.
We need further to investigate this whole setup.

**Comment by olafmol** [comment]
If this is an issue with the routing difficulties in the "run it all on one machine including mesos/marathon" Vamp setup, it might be better to change this Vamp version to using the Docker driver instead.

**Comment by tnolet** [comment]
This is due to routing issues with Docker --net=host and boot2docker. Somehow this changed in recent boot2docker versions...Ill replace it with the Docker driver.
